CREATE TABLE IF NOT EXISTS alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    deviceId TEXT NOT NULL,
    rule TEXT NOT NULL,
    value REAL,
    triggered_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
